name: Lint, format and type check

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Ruff format && check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: lint
        run: ruff check .

      - name: format check
        run: ruff format --check .

  pyright:
    name: type check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run pyright
        shell: bash -l {0}
        run: micromamba run -n plaid-meshops pyright
